# Generated by Django 2.2.5 on 2019-11-12 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=50, unique=True)),
                ('answered_questions', models.ManyToManyField(related_name='answered_questions', to='quizzes.Question')),
                ('current_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.Question')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_hosting_set', to=settings.AUTH_USER_MODEL)),
                ('players', models.ManyToManyField(to='games.Player')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_game_set', to='quizzes.Quiz')),
                ('unanswered_questions', models.ManyToManyField(related_name='unanswered_questions', to='quizzes.Question')),
            ],
        ),
    ]
