# Generated by Django 2.2.5 on 2019-10-06 17:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        ('users', '0002_auto_20190923_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_set', to='quizzes.Quiz')),
                ('players', models.ManyToManyField(related_name='player_set', to='users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gameName', models.CharField(max_length=50)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_hosting_set', to='users.User')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_game_set', to='quizzes.Quiz')),
            ],
        ),
    ]
