# Generated by Django 2.2.5 on 2019-10-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
