# Generated by Django 2.2.8 on 2020-01-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
