# Generated by Django 2.2.5 on 2019-10-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20191006_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameName',
            new_name='game_name',
        ),
    ]
