# Generated by Django 2.2.8 on 2020-01-27 17:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        ('games', '0002_game_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerdQuestion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.Game')),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions_lost', to='games.Player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quizzes.Question')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions_won', to='games.Player')),
            ],
        ),
    ]
