# Generated by Django 2.2.5 on 2019-10-26 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        ('games', '0003_auto_20191026_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='answered_questions',
            field=models.ManyToManyField(related_name='answered_questions', to='quizzes.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='current_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizzes.Question'),
        ),
        migrations.AddField(
            model_name='game',
            name='unanswered_questions',
            field=models.ManyToManyField(related_name='unanswered_questions', to='quizzes.Question'),
        ),
    ]
