# Generated by Django 2.2.8 on 2020-01-27 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
        ('games', '0003_answerdquestion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnswerdQuestion',
            new_name='AnsweredQuestion',
        ),
    ]
