# Generated by Django 2.2.5 on 2019-10-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20191027_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(db_constraint=False, to='quizzes.Question'),
        ),
    ]
