# Generated by Django 2.2.5 on 2019-10-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20191009_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='prompt',
            field=models.CharField(max_length=100),
        ),
    ]
