# Generated by Django 2.2.5 on 2019-10-27 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20191027_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(to='quizzes.Question'),
        ),
    ]
